language: cpp

branches:
  only: 
    - master

env:
- PYTHON_BUILD_VERSION=3.7

dist: xenial
sudo: false

addons:
  apt:
    packages:
    - git 
    - cmake 
    - build-essential 
    - libxmu-dev 
    - libxi-dev 
    - xorg-dev
    - freeglut3-dev 
    - libglfw3-dev 
    - libglew-dev
    - python3-dev 
    - python3-pip
    - python3-setuptools

script: |
  git submodule init
  git submodule update
  cd src_cpp/external/glfw
  cmake .
  make
  cd ../../../
  cd test/googletest
  mkdir build
  cd build
  cmake ..
  make
  cd ../../../
  pip3 install -e .
  cd test_cpp
  ls googletest/build/googlemock/gtest
  mkdir buildMake
  cd buildMake
  cmake ..
  make
  make test 
  cd ../../
  cd examples_cpp
  mkdir buildMake
  cd buildMake
  cmake ..
  make -i
  cd ..
  ls bin/  
  cd .. 
  cd module_py
  mkdir buildMake
  cd buildMake
  cmake ..
  make  
  cd ../../